version: "3.8"
services:
  app:
    build: .
    command: yarn start:prod
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017