version: "3.8"
services:
  app-test:
    build: .
    command: yarn test
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongo-test
    depends_on:
      - mongo-test
    environment:
      - NODE_ENV=test
      - TESTING_IN_DOCKER=true

  mongo-test:
    image: mongo:latest
    volumes:
      - ./data-test:/data/db
    ports:
      - 3001:27017