version: "3.8"
services:
  app:
    build: .
    command: yarn test:all
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:3001

  mongo:
    image: mongo:latest
    volumes:
      - ./data-test:/data/db
    ports:
      - 3001:27017